setPIN = "Set PIN"
registration = "Registration"
authorization = "Authorization"
items = "Items"
newItem = "New item"
quit = "Quit"
newItemText = "New Item Text"
newItemLogin = "New Item Login"
newItemCard = "New Item Card"
newItemFile = "New Item File"
back = "Back"
itemsFrontControl = "(r) remove\n(b) back \n(q) to quit"
login = "Login"
password = "Password"
passwordRetry = "Password retry"
save = "Save"
success = "Success"
pin = "PIN"
pinRetry = "PIN retry"
text = "Text"
cardNumber = "Card Number"
validDate = "Valid Date"
payer = "Payer"
file = "File"
type = "Type"
added = "Added"
unknownType = "Unknown Type"
card = "Card"
name = "Name"
link = "Link"