setPIN = "Установка PIN"
registration = "Регистрация"
authorization = "Авторизация"
items = "Записи"
newItem = "Новая запись"
quit = "Выход"
newItemText = "Добавление текста"
newItemLogin = "Добавление логина/пароля"
newItemCard = "Добавление карты"
newItemFile = "Добавление файла"
back = "Назад"
itemsFrontControl = "(r) удалить\n(b) назад \n(q) закрыть"
login = "Логин"
password = "Пароль"
passwordRetry = "Повтор пароля"
save = "Сохранить"
success = "Успех"
pin = "PIN"
pinRetry = "PIN повтор"
text = "Текст"
cardNumber = "Номер карты"
validDate = "Дата истечения"
payer = "Плательщик"
file = "Файл"
type = "Тип"
added = "Добавлен"
unknownType = "Неизвестный тип"
card = "Карта"
name = "Название"
link = "Ссылка"